apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openttd-saves
  labels:
    app: openttd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openttd-content-download
  labels:
    app: openttd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
