apiVersion: v1
kind: Service
metadata:
  name: openttd-service-tcp
  namespace: openttd
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: openttd
spec:
  type: LoadBalancer
  loadBalancerIP: 10.13.8.15
  ports:
    - name: openttd-udp
      port: 3979
      protocol: UDP
  selector:
    app: openttd
---
apiVersion: v1
kind: Service
metadata:
  name: openttd-service-udp
  namespace: openttd
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: openttd
spec:
  type: LoadBalancer
  loadBalancerIP: 10.13.8.15
  ports:
    - name: openttd-tcp
      port: 3979
      protocol: TCP
  selector:
    app: openttd
---
apiVersion: v1
kind: Service
metadata:
  name: openttd-service-admin-tcp
  namespace: openttd
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: openttd
spec:
  type: LoadBalancer
  loadBalancerIP: 10.13.8.15
  ports:
    - name: openttd-admin-tcp
      port: 3977
      protocol: TCP
  selector:
    app: openttd
